### Load libraries

In [1]:
import pandas as pd
import numpy as np

### Import data from pickles

In [2]:
train_df = pd.read_pickle('pickles/train_df.pkl')
test_df = pd.read_pickle('pickles/test_df.pkl')

### Vectorization

In [3]:
# apply vectorization on train set
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
texts_train = train_df['corpus'].tolist()
X_train = cv.fit_transform(texts_train).toarray()
y_train = train_df.iloc[:, -1].values

In [4]:
# ...test set
texts_test = test_df['corpus'].tolist()
X_test = cv.transform(texts_test).toarray()
y_test = test_df.iloc[:, -1].values

### Naive Bayes model

In [5]:
# import and train model
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [6]:
# predictions
y_pred = classifier.predict(X_test)

In [7]:
# accuracy score and confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
print(accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred, labels=['Automotive', 'Computers', 'Politics', 'Religion', 'Science', 'Sports'])
print(cm)

0.8947073648837861
[[ 721   13   23    4   31    2]
 [   4 1819    8   11  112    1]
 [   4    5  958   45   35    3]
 [   0   14   63  862   28    1]
 [  24  156   74   42 1281    2]
 [   2   17    9   11    8  749]]


### Support Vector Machine model

In [8]:
# import and train model
from sklearn.svm import LinearSVC
classifier = LinearSVC(max_iter=2000)
classifier.fit(X_train, y_train)

LinearSVC(max_iter=2000)

In [9]:
#preditions
y_pred = classifier.predict(X_test)

In [10]:
# accuracy score and confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
print(accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

0.8401008120974517
[[ 690   38   12    5   45    4]
 [  30 1788   13   13  103    8]
 [  22   39  801  100   67   21]
 [   8   36   47  814   55    8]
 [  42  222   74   39 1188   14]
 [  13   27   10   13   14  719]]
